# Generated by Django 5.2 on 2025-04-27 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Empleado')),
                ('entry_date', models.DateField(verbose_name='Fecha de Ingreso')),
                ('created_at', models.DateField(verbose_name='Fecha de Creación del registro')),
                ('modified_at', models.DateField(verbose_name='Fecha de Ultima Modificación')),
            ],
        ),
        migrations.CreateModel(
            name='VacationTaken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacation_days', models.IntegerField(verbose_name='Cantidad de días tomados')),
                ('vacation_date', models.DateField(verbose_name='Fecha de solicitud de vacaciones')),
                ('employ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calcuvaca_site.employ')),
            ],
        ),
    ]
